name: Post Fork Initialization

on:
  push:
    branches:
      - main

jobs:
  post-fork:
    if: github.repository != 'rhiokim/.seed-ts'
    name: Post Fork Initialization

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/post-fork.js`)
            script({ github, context })

      - name: Remove Files
        uses: rhiokim/remove-files-action@v1
        with:
          files: './.github/workflows/post-fork.yaml ./.github/workflows/post-fork.js'

      - name: After run
        run: |
          cat ./README.md
          cat ./package.json

      # - name: push
      #   uses: github-actions-x/commit@v2.1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: 'chore: replaces template variables'
      #     rebase: 'true'