name: Post Fork Initialization

on:
  push:
    branches:
      - main

jobs:
  post-fork:
    if: github.repository == 'rhiokim/.seed-ts'
    name: Post Fork Initialization

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # - name: Compare forked name of repository
      #   run: |
      #     echo "${{ github.repository }}"
      #     node -p -e "process.exit(1)"

      - name: Remove Files
        uses: rhiokim/remove-files-action@v1
        with:
          files: './.github/workflows/post-fork.yaml'